version: '3.8'

services:
  php-api:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: team
      MYSQL_PASSWORD: Te@m1234!
      MYSQL_DATABASE: management
    volumes:
      - ./data:/var/lib/mysql